# =============================================================================
# grimlock namespace with ambient mesh label
# =============================================================================
# Enables ambient mesh for workloads. Also labels default.
# =============================================================================

apiVersion: v1
kind: Namespace
metadata:
  name: default
  labels:
    istio.io/dataplane-mode: ambient
---
apiVersion: v1
kind: Namespace
metadata:
  name: grimlock
  labels:
    istio.io/dataplane-mode: ambient
